version: '3.9'
services:
  backend:
    build: .
    command: python /micropylik/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/micropylik
    ports:
      - 8000:8000
    depends_on:
      - db
  
  db:
    image: mysql:5.7.22
    restart: always
    environment: 
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
    volumes: 
      - .dbdata:/var/lib/mysql
    ports:
      - 33066:3306   
